apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: heapster
  namespace: kube-system
spec:
  replicas: 1
  template:
    metadata:
      labels:
        task: monitoring
        k8s-app: heapster
    spec:
      containers:
      - name: heapster
        image: gcr.io/google_containers/heapster:v1.1.0
        imagePullPolicy: IfNotPresent
        command:
        - /heapster
        - "--source=kubernetes:http://10.0.0.1:8080?inClusterConfig=false&useServiceAccount=true&auth="

        - --sink=influxdb:http://monitoring-InfluxDb-Service Ip:8086
